- name: install the nginx server
  hosts: frontend
  become: yes
  vars:
  vars_prompt:
  tasks:
    - name: install nginx server
      ansible.builtin.dnf:
        name: nginx
        state: latest

    - name: start and enable nginx
      ansible.builtin.service:
        name: start nginx
        state: started
        enabled: yes

    - name: delete the default website
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: create html directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name: download and extract frontend code
      ansible.builtin.unarchive:
        src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
        dest: /tmp/frontend.zip
        remote_src: yes 

    - name: copy the backend configuration
      ansible.builtin.copy:
        src: expense.conf       
        dest: /etc/nginx/default.d/expense.conf
        

    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted    
